version: '3.7'

services:
  postgres-booking:
    image: postgres:latest
    container_name: postgres-booking
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1111
      POSTGRES_DB: BookingDb
    ports:
      - "5433:5432"
    volumes:
      - postgres_data_bookings:/var/lib/postgresql/data
    networks:
      - backend_network
        
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres-booking
    networks:
      - backend_network

networks:
  backend_network:
    driver: bridge
    
volumes:
  postgres_data_bookings: