version: '3.7'

services:
  postgres-booking:
    image: postgres:latest
    container_name: postgres-booking
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1111
      POSTGRES_DB: BookingDb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_bookings:/var/lib/postgresql/data

networks:
  backend_network:
    driver: bridge
    
volumes:
  postgres_data_bookings: